Document: exscalibar
Title: Debian exscalibar Manual
Author: <insert document author here>
Abstract: This manual describes what exscalibar is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/exscalibar/exscalibar.sgml.gz

Format: postscript
Files: /usr/share/doc/exscalibar/exscalibar.ps.gz

Format: text
Files: /usr/share/doc/exscalibar/exscalibar.text.gz

Format: HTML
Index: /usr/share/doc/exscalibar/html/index.html
Files: /usr/share/doc/exscalibar/html/*.html
